name: ci

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            registry.home.example.com/example/example
          tags: |
            type=semver,pattern={{version}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: registry.home.example.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Create Tag Artifact
        run: echo "${{ steps.meta.outputs.tags }}" > tags.txt
      - name: Create Tag Output
        id: tag
        run: echo "::set-output name=tag::$(head -n 1 ./tags.txt)"
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

  updategit:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Update Manifest Repo
        uses: actions/checkout@v3
        with:
          repository: 'example/repo-name'
          token: ${{ secrets.GIT_TOKEN }}
          ref: main
      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          chmod +x /usr/bin/yq
      - name: Modify Images
        run: |
          git config --global user.name "example"
          git config --global user.email "example@example.com"
          cd manifest
          yq -i e ".spec.template.spec.containers[0].image = \"${{ needs.docker.outputs.tag }}\"" manifest.yml
          git add .
          git commit -m "Updated image to ${{ needs.docker.outputs.tag }} by Gitea Actions"
          git push
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_TOKEN }}
